baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Cynteo Alert Bridge Docs'
theme = 'hugo-theme-relearn'

images = ['images/cto_logo.png']

[params]
base = '/CAB-PUBLIC-DOCS-TESTING'
images = ['images/cto_logo.png']
themeVariant = [
  { identifier = 'auto', name = 'Zen Light/Dark', auto = [
    'zen-light',
    'zen-dark',
  ] },
  { identifier = 'zen-light' },
  { identifier = 'zen-dark' },
]
disableLandingPageButton = false
landingPageName = '<i class="fa-fw fas fa-home"></i> Home'
titleSeparator = '|'
sidebarmenus = [
  { type = 'menu', identifier = 'defined', main = true, disableTitle = true },
  # { type = 'page', identifier = 'home', main = true, disableTitle = true, pageRef = '' },
  # { type = 'menu', identifier = 'shortcuts', main = false, disableTitle = false },
]
disableInlineCopyToClipBoard = true
disableAnchorScrolling = false
alwaysopen = true
collapsibleMenu = false
disableRootBreadcrumb = false

[[menu.defined]]
identifier = 'overview'
parent = 'home'
name = 'Overview'
pageRef = '/overview'
weight = 1
params = { alwaysopen = true, collapsibleMenu = true }

[[menu.defined]]
identifier = 'quicklinks'
parent = 'home'
name = 'Quick Links'
pageRef = '/quicklinks'
weight = 2
params = { alwaysopen = true, collapsibleMenu = true }


[[menu.defined]]
identifier = 'usage'
parent = 'home'
name = 'Usage Guide'
pageRef = '/usage'
weight = 3
params = { alwaysopen = true, collapsibleMenu = true }


[[menu.defined]]
identifier = 'actionGroup'
parent = 'usage'
name = 'Action Group Setup'
pageRef = '/usage/actiongroup/actionGroup'
weight = 3
params = { alwaysopen = true, collapsibleMenu = true }


[[menu.defined]]
identifier = 'priorityMapping'
parent = 'usage'
name = 'Priority Mapping Setup'
pageRef = '/usage/prioritymapping/priorityMapping'
weight = 3
params = { alwaysopen = true, collapsibleMenu = true }


[[menu.defined]]
identifier = 'severityFiltering'
parent = 'usage'
name = 'Severity Filtering Setup'
pageRef = '/usage/severityfiltering/severityFiltering'
weight = 3
params = { alwaysopen = true, collapsibleMenu = true }
