baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Cynteo Alert Bridge Docs'
theme = 'hugo-theme-relearn'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

images = ['images/cto_logo.png']

[params]
base = '/CAB-PUBLIC-DOCS-TESTING'
images = ['images/cto_logo.png']
themeVariant = [
  { identifier = 'auto', name = 'Zen Light/Dark', auto = [
    'zen-light',
    'zen-dark',
  ] },
  { identifier = 'zen-light' },
  { identifier = 'zen-dark' },
]
disableLandingPageButton = false
landingPageName = '<i class="fa-fw fas fa-home"></i> Home'
titleSeparator = '|'
sidebarmenus = [
  { type = 'menu', identifier = 'defined', main = true, disableTitle = true },
  # { type = 'page', identifier = 'home', main = true, disableTitle = true, pageRef = '' },
  # { type = 'menu', identifier = 'shortcuts', main = false, disableTitle = false },
]
disableInlineCopyToClipBoard = true
disableAnchorScrolling = false
alwaysopen = true
collapsibleMenu = false
disableRootBreadcrumb = false
# clarityId = 'prb1m4vask' # AVM-Test
clarityId = 'p0l7yeco82' # Azure-Verified-Modules
custom_js = ['js/tags.js']

[markup]
defaultMarkdownHandler = 'goldmark'
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[markup.goldmark.parser]
autoHeadingID = true

[[menu.defined]]
identifier = 'overview'
parent = 'home'
name = 'Overview'
pageRef = '/overview'
weight = 1
params = { alwaysopen = true, collapsibleMenu = true }


[[menu.defined]]
identifier = 'usage'
parent = 'home'
name = 'Usage Guide'
pageRef = '/usage'
weight = 3
params = { alwaysopen = true, collapsibleMenu = true }