baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Cynteo Alert Bridge Docs'
theme = 'hugo-theme-relearn'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  themeVariant = 'neon'
